version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./user-service:/app
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
